inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - 'Gemfile'
    - '**/*.rb'
  Exclude:
    - 'lib/bibtex/parser.rb'
    - 'lib/bibtex/name_parser.rb'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
